pub(crate) mod code_exec_popup;
pub(crate) mod code_exec_popup_layout;
mod code_exec_popup_render_base;
mod code_exec_popup_render_buttons;
pub(crate) mod code_exec_popup_text;
pub(crate) mod file_patch_popup;
pub(crate) mod file_patch_popup_layout;
pub(crate) mod file_patch_popup_text;
pub(crate) mod model_popup;
pub(crate) mod prompt_popup;
pub(crate) mod question_review_popup;
pub(crate) mod terminal_popup_layout;
