mod base_frame;
mod button;
mod code_exec;
mod file_patch;
mod frame;
pub(crate) mod help;
pub(crate) mod jump;
mod layout;
mod model;
mod overlay_root;
pub(crate) mod overlay_table;
mod prompt;
mod question_review;
mod root;
pub(crate) mod summary;
pub(crate) mod tab_bar;
pub(crate) mod terminal;

pub(crate) use frame::FrameLifecycle;
pub(crate) use root::RootWidget;
